### ISSUE TITLE
ZED2i camera doesn't work on this

### ISSUE THREAD

**Issue by oldkimchi** [stereolabs/zed-3d-social-distancing#3]
I'm currently using ZED2i on windows 10.

when running ./ZED_Object_Detection_Viewer after building the program, 

it says "ERROR : Use ZED2 Camera only"

how do you fix this problem?

![43453](https://user-images.githubusercontent.com/45351939/126156803-8289b6ce-c17f-4c41-9908-fafee408d1fa.png)

**Comment by Myzhar** [comment]
@oldkimchi I just pushed the fix in the master branch. You can pull it and recompile it to use the SW with your ZED2i.

**Comment by oldkimchi** [comment]
> @oldkimchi I just pushed the fix in the master branch. You can pull it and recompile it to use the SW with your ZED2i.

@Myzhar thank you for your work. I did download again, rebuild it and run it. the error message's gone, I've got no errors.

however, ZED2i camera doesn't display anything somehow, it seems GPU was working but there's no action from the camera.

any idea on that? 
![34444](https://user-images.githubusercontent.com/45351939/126251739-36fd98d3-538c-45e9-9e80-4240b8f24204.png)

**Comment by oldkimchi** [comment]
I've got ZED SDK v3.5.0 with cuda 10.2 by the way, other ZED tutorials work just fine.

**Comment by Myzhar** [comment]
@oldkimchi the first time that you use a new model for AI detection you need to download it from the internet and wait for the SDK to optimize it for your GPU card. This operation can take a few minutes, but only the first time

**Comment by oldkimchi** [comment]
@Myzhar  hm..I've done several times but still won't work. 

there's no single error message but nothing comes up. it's pretty frustrating.


![22222222222](https://user-images.githubusercontent.com/45351939/126482321-63fa682c-57b3-41b3-907e-25dda0885624.png)

**Comment by Myzhar** [comment]
Have you tried the Object Detection example in the zed-examples repository?
https://github.com/stereolabs/zed-examples
Let me know if that works

**Comment by oldkimchi** [comment]
sorry about the late reply, I've been away for a while
it turned out numpy version on anaconda base somehow get involved on my conda env.
once I downgraded numpy on base, it works just fine. thank you for your help! @Myzhar
